"""empty message

Revision ID: fe3092fb250b
Revises: 
Create Date: 2019-03-05 10:23:54.823913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3092fb250b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=128), nullable=True),
    sa.Column('wdate', sa.Date(), nullable=True),
    sa.Column('weight_of_ort', sa.String(length=128), nullable=True),
    sa.Column('weight_of_compost', sa.String(length=128), nullable=True),
    sa.Column('groups', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_groups'), 'data', ['groups'], unique=False)
    op.create_index(op.f('ix_data_notes'), 'data', ['notes'], unique=False)
    op.create_index(op.f('ix_data_wdate'), 'data', ['wdate'], unique=False)
    op.create_index(op.f('ix_data_weight_of_compost'), 'data', ['weight_of_compost'], unique=False)
    op.create_index(op.f('ix_data_weight_of_ort'), 'data', ['weight_of_ort'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_weight_of_ort'), table_name='data')
    op.drop_index(op.f('ix_data_weight_of_compost'), table_name='data')
    op.drop_index(op.f('ix_data_wdate'), table_name='data')
    op.drop_index(op.f('ix_data_notes'), table_name='data')
    op.drop_index(op.f('ix_data_groups'), table_name='data')
    op.drop_table('data')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
